import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { scripts, stylesheets } from "@/model";
import { LINKS } from "@/interface";
import Script from "next/script";
import { Footer } from "@/components/Footer";
import { GlobalThemeProvider } from "@/components/GlobalThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sudeep Dutta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {stylesheets.map((sheet: LINKS) => (
          <link key={sheet.id} rel="stylesheet" href={sheet.href} />
        ))}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased class="antialiased text-lg leading-[30px] font-primary text-dark dark:bg-semidark dark:text-white scrollbar-thumb-dark/25 scrollbar-track-dark/10 scrollbar-thin`}
      >
        <GlobalThemeProvider>
          <div id="preloader">
            <div className="loader_line"></div>
          </div>
          <Header />
          {children}
          <Footer />
        </GlobalThemeProvider>
        {scripts.map((script: LINKS) => (
          <Script key={script.id} src={script.href} />
        ))}
      </body>
    </html>
  );
}
